; PlatformIO Project Configuration File for Linorobot2 (ESP32 NodeMCU-32S)
; 
[platformio]
default_envs = esp32
[env]
platform = espressif32
framework = arduino
board = nodemcu-32s
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = min_spiffs.csv
monitor_speed = 921600

; Tự động lấy bản ROS 2 (Jazzy) từ biến môi trường máy tính
board_microros_distro = jazzy

; Tải các thư viện cần thiết cho robot
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    mcauser/i2cdetect
    jrowberg/I2Cdevlib-Core
    jrowberg/I2Cdevlib-ADXL345
    jrowberg/I2Cdevlib-AK8975
    jrowberg/I2Cdevlib-HMC5843
    jrowberg/I2Cdevlib-HMC5883L
    jrowberg/I2Cdevlib-ITG3200
    jrowberg/I2Cdevlib-MPU6050
    https://github.com/dthain/QMC5883L
    https://github.com/wollewald/INA219_WE
    https://github.com/arcao/Syslog
    SPI
    adafruit/Adafruit BusIO
    adafruit/Adafruit PWM Servo Driver Library
    madhephaestus/ESP32Servo
    madhephaestus/ESP32Encoder

# --- Cấu hình 1: Chạy dây cáp USB (Giao tiếp Serial) ---
[env:esp32]
board_microros_transport = serial
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
upload_protocol = esptool
build_flags =
    -I ../config
    -D __PGMSPACE_H_
    -D USE_ESP32_CONFIG

# --- Cấu hình 2: Chạy kết nối không dây qua WiFi ---
[env:esp32_wifi]
board_microros_transport = wifi
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
upload_protocol = esptool
build_flags =
    -I ../config
    -D __PGMSPACE_H_
    -D USE_ESP32_WIFI_CONFIG
    -D USE_STAY_CONNECTED